### ISSUE TITLE
i have questions

### ISSUE THREAD

**Issue by LogSkele** [kokonut27/PogRater#5]
1. what is the flask session for?
2. is there any other way to pass info from html to python without js?
3. can you explain the session module to me?

thanks, appreciate it :D

**Comment by kokonut27** [comment]
Uhh, so

1. to keep track of data in my case, but usually for session cookies
2. yes, with python being the backend, not js
3. uhh, so basically, what it does is that it keeps track of cookies from each session from the user. you can name the cookie whatever you want, make the cookies as files in my case, or as regular cookies (default im pretty sure). but usually, cookies arent used for storing these kinds of data, more of like small bits of info to store such as if they've visited a certain route or not.

hope this helps!

**Comment by LogSkele** [comment]
yes it does thx! :D

> sigh, theres always people more advanced in coding than me lol

**Comment by kokonut27** [comment]
np!
> ripp same lol
